# Custom Language File for Launcher Customizer

[ejs.app]
title = "NoHopeLauncher"

[ejs.landing]
mediaGitHubURL = "https://github.com/andy3471/NewHopeLauncher"
mediaLinkURL = "https://nohopelauncher.andyh.app"
mediaDiscordURL = "https://discord.gg/CXhp2ke"

[ejs.settings]
sourceGithubLink = "https://github.com/andy3471/NewHopeLauncher"
supportLink = "https://github.com/andy3471/NewHopeLauncher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO NOHOPE LAUNCHER"
welcomeDescription = "Welcome to NoHope Launcher! This launcher makes it easy to join modded Minecraft servers. All mods, configurations, and updates are handled automatically for you."
welcomeDescCTA = "You are just a few clicks away from playing."
